name: Build Demo

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-demo:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/JitterDemo

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
