name: JitterTests

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  id-token: write
  contents: write
  checks: write
  actions: write

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/JitterTests

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test -c Release --no-restore --test-adapter-path:. --logger "trx;LogFileName=test-results.trx"

    - name: TestReport
      uses: dorny/test-reporter@v1
      if: always()    # Run this step even if "Test" fails
      with:
        name: JitterTests
        path: ./src/JitterTests/TestResults/test-results.trx
        reporter: dotnet-trx

    - name: TestDP
      run: dotnet test -c Release -p:DefineConstants="USE_DOUBLE_PRECISION" --no-restore --test-adapter-path:. --logger "trx;LogFileName=test-results-dp.trx"
      if: always()    # Run this step even if "Test" fails

    - name: TestReportDP
      uses: dorny/test-reporter@v1
      if: always()    # Run this step even if "TestDP" fails
      with:
        name: JitterTestsDP
        path: ./src/JitterTests/TestResults/test-results-dp.trx
        reporter: dotnet-trx
