name: JitterTests

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  id-token: write
  contents: write
  checks: write
  actions: write

env:
  CONFIGURATION: Release
  TEST_RESULTS_DIR: ./TestResults

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/JitterTests

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Run Tests
        run: |
          mkdir -p ${{ env.TEST_RESULTS_DIR }}
          
          # Run Single Precision Tests
          dotnet test --configuration ${{ env.CONFIGURATION }} --no-restore \
            --test-adapter-path:. --logger "trx;LogFileName=single-precision.trx"

          # Run Double Precision Tests
          dotnet test --configuration ${{ env.CONFIGURATION }} -p:DefineConstants="USE_DOUBLE_PRECISION" --no-restore \
            --test-adapter-path:. --logger "trx;LogFileName=double-precision.trx"
        if: always()