name: JitterTests

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  id-token: write
  contents: write
  checks: write
  actions: write

env:
  CONFIGURATION: Release
  TEST_RESULTS_DIR: ./TestResults

jobs:
  build-and-test:
    name: Build and Test (${{ matrix.precision }})

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        precision:
          - single
          - double

    defaults:
      run:
        working-directory: ./src/JitterTests

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build single-precision tests
        if: matrix.precision == 'single'
        run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Build double-precision tests
        if: matrix.precision == 'double'
        run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore -p:DoublePrecision=true

      - name: Run single-precision tests
        if: matrix.precision == 'single'
        run: |
          mkdir -p ${{ env.TEST_RESULTS_DIR }}

          dotnet test --configuration ${{ env.CONFIGURATION }} --no-restore \
            --test-adapter-path:. --logger "trx;LogFileName=single-precision.trx"

      - name: Run double-precision tests
        if: matrix.precision == 'double'
        run: |
          mkdir -p ${{ env.TEST_RESULTS_DIR }}

          dotnet test --configuration ${{ env.CONFIGURATION }} --no-restore -p:DoublePrecision=true \
            --test-adapter-path:. --logger "trx;LogFileName=double-precision.trx"